Improve cmd
wsdjeg/SpaceVim pull request #1339
Opened 2018-01-28 02:08 UTC by wsdjeg

2018-01-29 06:06 UTC, Gabirel commented on docs/cn/install.cmd
> +    echo "[OK] 测试成功. 开始下一个测试..."
Please make sure they have the same indent.

2018-01-29 06:07 UTC, Gabirel commented on docs/cn/install.cmd
> +    echo "[OK] 测试成功. 开始下一个测试..."
And it applies to the following lines

2018-01-29 07:04 UTC, Gabirel requested changes

2018-01-29 07:04 UTC, Gabirel commented on docs/cn/install.cmd
> +  echo "[WARNING] 无法在你的 PATH 中发现 'gvim.exe' 命令. 安装已继续..."
“安装已继续” ==> "但，安装仍可继续"

2018-01-29 16:12 UTC, wsdjeg commented on docs/cn/install.cmd
> +  echo "[WARNING] 无法在你的 PATH 中发现 'gvim.exe' 命令. 安装已继续..."
@Gabirel 你知不知道，cmd 里面怎么彩色输出呀，我想整个脚本流程及界面和 bash 一样的

2018-01-30 18:42 UTC, Gabirel commented on docs/cn/install.cmd
> +  echo "[WARNING] 无法在你的 PATH 中发现 'gvim.exe' 命令. 安装已继续..."
No, I'm not familiar with powershell

2018-02-02 12:16 UTC, merged