Add clever f
wsdjeg/SpaceVim pull request #1460
Opened 2018-03-04 01:08 UTC by wsdjeg

ref: #1436

2018-03-04 17:47 UTC, jetm commented on autoload/SpaceVim.vim
>  " Unite work flow leader of SpaceVim. Default is `f`.
Here should says: Default is `\f`.

2018-03-04 17:49 UTC, jetm commented on autoload/SpaceVim.vim
>  " Denite work flow leader of SpaceVim. Default is `F`.
I was expecting F will be \F as well as for unite.

2018-03-04 17:51 UTC, jetm requested changes
I will make these changes before merge it

2018-03-05 14:38 UTC, wsdjeg commented
maybe we can remove this option, and denite layer is same as unite layer. also same as ctrp layer, user should use only one of them, and these there layer maybe should has same key bindings. the prefix can be setted when loadding layer.

2018-03-14 13:23 UTC, merged

2018-03-22 07:15 UTC, zhigang1992 commented
hey guys, I'm having trouble use denite's lead key, which was `F`. Should that be mentioned somewhere and how should I fix that?

2018-03-22 07:35 UTC, wsdjeg commented
that was removed. you can load denite layer. and read denite layer documentation.