Add vimcompatible mode
wsdjeg/SpaceVim pull request #1596
Opened 2018-04-03 15:16 UTC by wsdjeg

2018-04-04 04:06 UTC, NGenetzky commented
It would appear that the following idiom should be used to set defaults (rather than simple assignments):
```
let g:spacevim_windows_smartclose = get(g:, 'spacevim_windows_smartclose', 'q')
```
I believe it would be more logical to keep the compatible close to the default, such as:
```
if g:spacevim_vimcompatible == 0
  let g:spacevim_windows_smartclose = get(g:, 'spacevim_windows_smartclose', 'q')
else
  " TODO: Find suitable alternative to 'q', for now just disable.
  let g:spacevim_windows_smartclose = get(g:, 'spacevim_windows_leader', '')
endif
```

2018-04-04 04:08 UTC, NGenetzky commented on autoload/SpaceVim.vim
> +let g:spacevim_denite_leader            = '\f'
This does not appear to be related to 'vimcompatible' changes, but i assume that is intentional.

Don't forget to update the comment on line 77. Likewise, 73 and 75 appear to not match.

2018-04-04 04:10 UTC, NGenetzky requested changes
The way you use 'origin' sounds strange. 
I would recommend updating to something like: "In vimcompatible mode attempts are made to not map over existing vim key bindings"

2018-04-09 12:13 UTC, wsdjeg commented
@NGenetzky `autoload/SpaceVim.vim` is loaded before curstom config file `~/.SpaceVim.d/init.vim`, so no need to use `let g:spacevim_windows_smartclose = get(g:, 'spacevim_windows_smartclose', 'q')`

2018-04-12 12:47 UTC, merged